#!/bin/bash

. $(type -P utility.sh)

readonly ssh_dir="${HOME}/.ssh"
readonly name=$(<<<"$1" tr '[:upper:]' '[:lower:]')
readonly target="${ssh_dir}/${name}.gpg"
if test -f "${target}"; then
    gpg -d "${target}" 2>/dev/null | Command clip >/dev/null
else
    Error "'${target}' does not exist"
fi
