#!/bin/bash

. $(type -P utility.sh)

if (($# == 0)) && ! HasStdin; then
    read -r line
    echo "${line}" | xclip -selection clipboard
else
    if HasStdin; then
        set -- - "$@"
    fi
    cat "$@" | tee >(xclip -selection clipboard)
fi
