#!/bin/bash

. $(type -P utility.sh)

ssh_dir="${HOME}/.ssh"
name=$(tr '[:upper:]' '[:lower:]' <<<"$1")
target="${ssh_dir}/${name}.gpg"

if test -f "${target}"; then
    gpg -d "${target}" 2>/dev/null | Command clip >/dev/null
else
    Error "'${target}' does not exist"
fi
