#!/bin/bash

. $(type -P utility.sh)

opts=(--batch)
if HasStdin; then
    input='-'
else
    input="$1"
    if [[ "${input}" =~ \.gpg$ ]]; then
        output="${input%'.gpg'}"
        if test -f "${output}"; then
            Error "'${output}' already exists"
        fi
        opts+=(-o "${output}")
    fi
fi
gpg "${opts[@]}" -d "${input}"
