#!/bin/bash

. $(type -P utility.sh)

Command emacs-daemon-stop
for i in $(seq 10); do
    if ! Command emacs-daemon-exists; then
        break
    fi
    sleep 0.1
done
if Command emacs-daemon-exists; then
    Error 'emacs daemon have not be stopped'
fi
Command emacs-daemon-start
