#!/bin/bash

. $(type -P utility.sh)

opts=(--batch --personal-cipher-preferences camellia256)
if HasStdin; then
    input='-'
else
    input="$1"
    output="${input}.gpg"
    if test -f "${output}"; then
        Error "'${output}' already exists"
    fi
    opts+=(-o "${output}")
fi
gpg "${opts[@]}" -c "${input}"
