#!/bin/bash

. $(type -P utility.sh)

name=$(basename "$1")
dir=$(dirname "$1")
target="${name}.gpg"
Tempfiles
tmpfile="${tmpfiles_[0]}"

tar -c -f "${tmpfile}" -C "${dir}" -h -z "${name}"
gpg --batch --default-recipient-self -o "${target}" -e "${tmpfile}"
