#!/bin/bash

. $(type -P utility.sh)

name=$(basename "$1")
target="${name}.gpg"
if test -f "${target}"; then
    Error "'${target}' alread exists"
fi
tmp=$(Command compress "$1")
Trap "${tmp}"
opts=(--batch --personal-cipher-preferences camellia256)
gpg "${opts}" -o "${target}" -c "${tmp}" </dev/null
