#!/bin/bash

. $(type -P utility.sh)

name=$(basename "$1")
target="${name}.gpg"
if test -f "${target}"; then
    Error "'${target}' alread exists"
fi
tmp=$(Command compress "$1")
Trap "${tmp}"
gpg --batch --default-recipient-self -o "${target}" -e "${tmp}" </dev/null
