#!/bin/bash

. $(type -P utility.sh)

declare -a msg
for cmd in "$@"; do
    if ! which "${cmd}" &>/dev/null; then
        msg+=("'${cmd}' not found")
    fi
done
if Bound msg; then
    Error "${msg[@]}"
fi
