#!/bin/bash

. $(type -P utility.sh)

Command executable pwgen pwscore
if Bound 1 $#; then
    Command is-integer "$1"
    if (($1 < 8)); then
        Error 'too short for password'
    fi
    declare -i max_score=0
    for password in $(pwgen -sC $1); do
        if [[ "${password}" =~ [01IOlo] ]]; then
            continue
        fi
        declare -i score=$(<<<"${password}" pwscore 2>/dev/null)
        if ((max_score < score)); then
            strongest="${password}"
            max_score=score
        fi
    done
else
    for password in $(pwgen -s0C 32); do
        declare -i score=$(<<<"${password}" pwscore 2>/dev/null)
        if ((score == 100)); then
            strongest="${password}"
            max_score="${score}"
            break
        fi
    done
fi
if Bound strongest; then
    <<<"${strongest}" Command clip &>/dev/null
    echo "${strongest}" ${max_score}
fi
