#!/bin/bash

. $(type -P utility.sh)

if HasStdin; then
    input=$(cat -)
else
    if Bound 1 $#; then
        input="$1"
    else
        Error 'no argument specified'
    fi
fi
if test "${input}" -eq "${input}" &>/dev/null; then
    echo "${input}"
    exit
else
    Error "'${input}' is not integer"
fi
