#!/bin/bash

. $(type -P utility.sh)

if HasStdin; then
    input=$(cat -)
else
    input="$1"
fi
if test "${input}" -eq "${input}" &>/dev/null; then
    exit
else
    Error "'${input}' is not integer"
fi
