#!/bin/bash

. $(type -P utility.sh)

readonly local_dir="/media/${USER}/local"
if ! test -d "${local_dir}"; then
    if sudo mkdir -p "${local_dir}"; then
        sudo chown "${USER}:${USER}" "${local_dir}"
    else
        exit $?
    fi
fi
echo "${local_dir}"
