#!/bin/bash

. $(type -P utility.sh)

readonly local_dir=$(Command local-media-dir)
if test -z "${local_dir}"; then
    Error 'media directory not found'
fi
readonly gvfs_dir="${local_dir}/gvfs"
readonly src_dir='/run/user/1000/gvfs'
if test -e "${gvfs_dir}"; then
    Error "'${gvfs_dir}' is busy"
fi
ln -s "${src_dir}" "${gvfs_dir}"
