#!/bin/bash

. $(type -P utility.sh)

readonly local_dir=$(Command local-media-dir)
if test -z "${local_dir}"; then
    Error 'media directory not found'
fi
readonly idevice_dir="${local_dir}/idevice"
Command executable ifuse idevicepair
if test -e "${idevice_dir}"; then
    Error "'${idevice_dir}' is busy"
fi
while ! idevicepair pair; do
    if ! Command yesno 'Retry (Y/n)?'; then
        exit 1
    fi
done
mkdir -p "${idevice_dir}"
ifuse "${idevice_dir}"
