#!/bin/bash

. $(type -P utility.sh)

readonly config_file="${HOME}/.encfs6.xml"
readonly crypted_dir="${HOME}/Documents/Private"
readonly plaintext_dir="${HOME}/Private"
Command executable encfs
mkdir -p "${crypted_dir}" "${plaintext_dir}"
pass encfs | ENCFS6_CONFIG="${config_file}" encfs -S "${crypted_dir}" "${plaintext_dir}"
