#!/bin/bash

. $(type -P utility.sh)

readonly host="$1"
readonly target="${HOME}/${host}"
Command close-sshfs "${host}"
mkdir -p "${target}"
readonly home=$(ssh "${host}" 'echo "${HOME}"')
sshfs "${host}:${home}" "${target}" -o reconnect
