#!/bin/bash

. $(type -P utility.sh)

declare -i len="${1-32}" score=0 max=0
result=""
for pass in $(pwgen -Cs ${len}); do
    score=$(<<<"${pass}" pwscore 2>/dev/null || :)
    if ((max < score)); then
        max=${score}
        result="${pass}"
    fi
done
echo "${result}" | Command clip &>/dev/null
echo "${result}" "${max}"
