#!/bin/bash

. $(type -P utility.sh)

Server() {
    local pid=$(pgrep -u "${USER}" -a "$1" | fgrep "$*" | cut -d ' ' -f 1)
    test "${pid}" && kill ${pid}
    Command background "$@"
}

if (($# == 1)); then
    Server python3 -m http.server "$1"
else
    Server python3 -m http.server
fi
