#!/bin/bash

. $(type -P utility.sh)

Command stop-emacs-daemon
for i in $(seq 10); do
    if ! Command exists-emacs-daemon; then
        break
    fi
    sleep 0.1
done
if Command exists-emacs-daemon; then
    Error 'emacs daemon have not be stopped'
fi
Command start-emacs-daemon
