#!/bin/bash

. $(type -P utility.sh)
. "${BIN_DIR}/sed-aux"

while Bound 1 $#; do
    arg="$1"
    case "${arg}" in
        -a* | --address=* )
            Parse "$@" || shift $?
            Set address;;
        * )
            Error "unknown option '${arg}'";;
    esac
done
readonly script="${address-}p"
sed -n -e "${script}"
