#!/bin/bash

. $(type -P utility.sh)
. "${BIN_DIR}/sed-aux"

while Bound 1 $#; do
    arg="$1"
    case "${arg}" in
        -a* | --address=* )
            Parse "$@" || shift $?
            Set address;;
        -f* | --file=* )
            Parse "$@" || shift $?
            Set file;;
        * )
            Parse "$@" || Error "unknown option '${arg}'"
            shift 1
            Set command;;
    esac
done
if ! Bound command; then
    Error 'no command is specified'
fi
readonly script="${address-}a\\${command}"
if Bound file && test "${file}"; then
    if test -w "${file}"; then
        sed -i -e "${script}" "${file}"
    else
        sudo sed -i -e "${script}" "${file}"
    fi
else
    sed -e "${script}"
fi
