#!/bin/bash

. $(type -P utility.sh)
. "${BIN_DIR}/sed-aux"

declare -g parsed_ arg file address
while Bound 1 $#; do
    arg="$1"
    case "${arg}" in
        -a* | --address=* )
            Parse "$@" || shift $?
            Set address;;
        -f* | --file=* )
            Parse "$@" || shift $?
            Set file;;
        * )
            Error "unknown option '${arg}'";;
    esac
done
readonly script="${address-}d"
if Bound file && test "${file}"; then
    if test -w "${file}"; then
        sed -i -e "${script}" "${file}"
    else
        sudo sed -i -e "${script}" "${file}"
    fi
else
    sed -e "${script}"
fi
