#!/bin/bash

. $(type -P utility.sh)

Set() {
    if Bound "$1"; then
        Error "extra option '${arg}' is specified"
    fi
    declare -gr "$1"="${parsed_}"
}
Get() {
    while Bound 1 $#; do
        arg="$1"
        case "${arg}" in
            -a* | --address=* )
                Parse "$@" || shift $?
                Set address;;
            -f* | --file=* )
                Parse "$@" || shift $?
                Set file;;
            * )
                Error "unknown option '${arg}'";;
        esac
    done
}

declare -g parsed_ arg file address
Get "$@"
readonly script="${address-}d"
if Bound file && test "${file}"; then
    if test -w "${file}"; then
        sed -i -e "${script}" "${file}"
    else
        sudo sed -i -e "${script}" "${file}"
    fi
else
    sed -e "${script}"
fi
