#!/bin/bash

. $(type -P utility.sh)

Set() {
    if Bound "$1"; then
        Error "extra option '${arg}' is specified"
    fi
    declare -g "$1"="${parsed_}"
}
Get() {
    while ((0 < $#))
    do
        arg="$1"
        case "${arg}" in
            -a* | --address=* )
                Parse "$@" || shift $?
                Set address;;
            * )
                Error "unknown option '${arg}'";;
        esac
    done
}

declare -g parsed_ arg address
Get "$@"
script="${address-}p"
sed -n -e "${script}"
