#!/bin/bash

. $(type -P utility.sh)

name="$1"
value="$2"
file="${3-}"
s='[[:space:]]*'
pattern="^${s}${name}${s}="
script="${name}=${value}"
declare -i pos=$(Command line-number "${pattern}")
Command sed-write -a ${pos} "${script}" -f "${file}"
