#!/bin/bash

. $(type -P utility.sh)

name="$1"
value="$2"
s='[[:space:]]*'
pattern="^${s}${name}${s}="
script="${name}=${value}"
declare -i pos=$(Command line-number "${pattern}")
if (($# < 3)); then
    Command sed-write -a ${pos} "${script}"
else
    Command sed-write -a ${pos} "${script}" -f "$3"
fi
