#!/bin/bash

. $(type -P utility.sh)

Usage() {
    cat <<EOF
Usage : $(basename "$0") [DURATION] [COMMAND] [ARG]...

DESCRIPTION
    Execute COMMAND repeatedly until some output is received.
    If COMMAND is still running after DURATION, then kill it.

    If the command times out, then exit with status 124.
    If the script execution is successfull, then exit with status 0.
EOF
    exit
}
