#!/bin/bash

. $(type -P utility.sh)

Usage() {
    cat <<EOF
Usage : $(basename "$0") [DURATION] [COMMAND] [ARG]...

DESCRIPTION
    Execute COMMAND repeatedly until some output is received.
    If COMMAND is still running after DURATION, then kill it.

    If the command times out, then exit with status 124.
    If the script execution is successfull, then exit with status 0.
EOF
    exit
}

readonly limit="$1"
shift
readonly func="Loop${RANDOM}"
readonly cmd="${@@Q}"
readonly script=$(cat <<EOF
${func}() {
    while true; do
        local output=\$(bash -c ${cmd@Q})
        if test "\${output}"; then
            echo "\${output}"
            return
        fi
    done
}
${func}
EOF
         )
timeout "${limit}" bash -c "${script}"
