#!/bin/bash

. $(type -P utility.sh)

readonly local_dir=$(Command local-media-dir)
if test -z "${local_dir}"; then
    Error 'media directory not found'
fi
readonly gvfs_dir="${local_dir}/gvfs"

sudo unlink "${gvfs_dir}"
